version: '3.3'

services:
  bemysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 8084:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store_business_engine
    command:
      - mysqld
      - --server-id=1
      - --log-bin=/var/log/mysql/mysql-bin
      - --binlog_do_db=store_business_engine
